### ISSUE TITLE
Workshop - Konu Planlaması

### ISSUE THREAD

**Issue by fbayram** [adomorn/BelsisWorkshop#2]
İlk workshop deneyimini gerçekleştirdik.
Gelecek haftaki planda neler olabilir ve ne gibi durumları iyileştirebiliriz konusu üzerinde konuşmalıyız.

Bence gelecek hafta;

- Açılışta Git & GitHub kısmına dair kısa bir özet yapılabilir.

- .netCore da Authentication yönetimi ve oturum açma ile ilgili konuya bakabiliriz.(EntityFramework vb.)

- Ayrıca görüşmeler meet.jitsi üzerinden gitmesi bence daha makul olacaktır.

**Comment by volkansendag** [comment]
Böyle faydalı faaliyetlerin devamını dileriz.

**Comment by ademdurak** [comment]
@fbayram dediği gibi bencede açılışta Git & GitHub kısmına değinirsek bencede güzel olur. En azından basitçe bir projeyi githuba bağlayıp versiyon yönetimini github üzerinden yönetebilecek kadar bilgi sahibi olsak başlangıç için yeterlidir diye düşünüyorum.

Daha sonrasında;
- Basit bir bir kaç view oluşturup bu viewlar üzerinden devam edebiliriz.
- Geçen hafta api ye basitçe değinmiştik onun üzerinden gidip apiyi kullanarak veri tabanı işlemleri yapılabilir.

**Comment by fbayram** [comment]
Meet veya Discord üzerinden değil Youtube Canlı yayın üzerinden yapılacak. Teknik aksaklığı en aza indiririz gibi.

**Comment by adomorn** [comment]
tamam kimse ses çıkarmadığına göre
1. Github kısaca anlatılacak
2. .Net Core klasör yapısı anlatılacak
3. NpgSql ile DbContext oluşturulacak.
