### ISSUE TITLE
Workshop - Konu Planlaması 2

### ISSUE THREAD

**Issue by fbayram** [adomorn/BelsisWorkshop#4]
Merhabalar,

09.05.2020 tarihinde ikinci Workshop çalışmasını tamamladık.

Gelecek hafta yapmayı planladığımız Workshop için konu planlaması yapmamız gerekiyor. Bu issue altında yine fikir ve önerilerimizi tartışabiliriz.

Gelecek hafta;

- Razor Page ve MVC ile .netCore işlemlerini arayüz bazında yapılması incelenebilir. Bununla ilgili MVC yapısı ve geliştirme süreçlerini detaylandırabiliriz.

- Ayrıca Authentication ile .netCore üzerinde bir oturum yönetimi de detaylandırılabilir.

**Comment by adomorn** [comment]
Katılım yeteri kadar sağlanamadığından .net core workshopu belirsiz bir süreliğine askıya alınmıştır.
